- charts/healthz/README.md
- charts/healthz/templates/deployment.yaml
- charts/healthz/values.yaml
- cmd/healthz/main.go
- healthz/config/cli.go
- healthz/config/config.go
- healthz/utils/tls.go
I went the easy way: without modifications to monitoring package, adding certs to default cert pool.
> Add HTTPS support for kubernetes API

- agent/agent.go
- agent/server.go
- agent/server_test.go
- cmd/agent/main.go
Had to make some changes to build proper `TLS` config with a `CA` certificate - otherwise nodes with certificates signed by a `CA` won't connect.
> Add an option to specify a CA certificate file

- Makefile
- agent/server.go
- agent/server_test.go
- agent/status.go
Set the HTTP status code depending on the cluster status - e.g. use ServiceStatusUnavailable for degraded cluster state.
Add agent HTTP query test.
Updates https://github.com/gravitational/gravity/issues/2976.
> Set the HTTP status code depending on the cluster status

- monitoring/local_linux.go
- monitoring/sysctl.go
- monitoring/sysctl_checkers.go
We encountered an issue on RHEL 7.4 based kernels where pods could get stuck in the terminating state. It appears this is related to the following docker issue: https://github.com/moby/moby/issues/22260
Docker has decided to set the sysctl on startup, but older versions of docker will not do this. I've also added a directive to not report an error if the sysctl option isn't found. Based on the comments in https://github.com/moby/moby/pull/34886/files not all kernels will have this particular sysctl key, so we don't want to report errors if the key isn't on the particular kernel version which won't have this issue.
Cheers,
> Add check for fs.may_detach_mounts not being set

- monitoring/boot_config_linux.go
- monitoring/boot_config_linux_test.go
- monitoring/cgroup.go
- monitoring/cgroup_test.go
- monitoring/fs_linux.go
- monitoring/modules.go
- monitoring/modules_test.go
- monitoring/os_linux.go
- monitoring/os_linux_test.go
- monitoring/storage.go
- monitoring/storage_test.go
- monitoring/systemd.go
This will avoid mistakes when checkers are initialized directly and panic when used.
> Unexport checker types that require non-trivial initialization

- agent/server_test.go
- monitoring/modules.go
- monitoring/modules_test.go
Update kernel module checker to validate kernel modules with alternative names (for example, bridge netfilter which is called either `br-netfilter` or `bridge` depending on the distribution).
Fixes https://github.com/gravitational/gravity/issues/3303.
> Update kernel module checker to validate modules with alternative names

- agent/client.go
- agent/server.go
Result:
```
[root@sergei-dev-2 ~]# nmap --script +ssl-enum-ciphers -p 7575 10.162.0.14
Starting Nmap 6.40 ( http://nmap.org ) at 2018-06-14 18:28 UTC
Nmap scan report for sergei-dev-2.c.kubeadm-167321.internal (10.162.0.14)
Host is up (0.000088s latency).
PORT     STATE SERVICE
7575/tcp open  unknown
| ssl-enum-ciphers: 
|   TLSv1.2: 
|     ciphers: 
|       TLS_RSA_WITH_3DES_EDE_CBC_SHA - strong
|       TLS_RSA_WITH_AES_128_CBC_SHA - strong
|       TLS_RSA_WITH_AES_128_GCM_SHA256 - strong
|       TLS_RSA_WITH_AES_256_CBC_SHA - strong
|       TLS_RSA_WITH_AES_256_GCM_SHA384 - strong
|     compressors: 
|       NULL
|_  least strength: strong
Nmap done: 1 IP address (1 host up) scanned in 0.41 seconds
```
> Use TLS1.2 on port 7575

- monitoring/os_linux.go
- monitoring/os_linux_test.go
Revisit OS release/version parsing:
- do not use distributor ID as output by "lsb_release". The distributor `ID` is not the same as OS `ID` from /etc/os-release and is not useful in validation. `lsb_release` is only used to fetch the release version (if available)
- allow name/like input be regular expression patterns to extend the matcher's flexibility.
- handle comments in /etc/os-release file
- handle `name=value` pairs where value contains `=` during parsing of /etc/os-release
Updates https://github.com/gravitational/telekube/issues/3491.
> Improve OS release/version parsing

- monitoring/port.go
- monitoring/procfs_net.go
For some reason all udp sockets get "close" state so with yesterday's fix they are always skipped. Should only filter out time-wait sockets.
> Fix port checker.

- agent/agent.go
- agent/client.go
- agent/server.go
- agent/server_test.go
- cmd/agent/main.go
- cmd/agent/status.go
- monitoring/modules_test.go
Setup satellite monitoring ports to use mTLS authentication.
https://github.com/gravitational/gravity.e/issues/3726
I did a bit of refactoring to support this as well:
- When receiving an HTTP request, avoid invoking the gRPC client to localhost, and instead just invoke the gRPC service directly in process.
- I think some of the tests are broken unrelated to this change, I fixed a couple but I think some tests are still broken.
> use mTLS for client authentication

- monitoring/defaults_linux.go
- monitoring/defaults_linux_test.go
- monitoring/inotify.go
- monitoring/inotify_linux.go
- monitoring/inotify_linux_test.go
I've seen a couple customers run into a scenario where they've run out of inotify watches. Unfortunately, the kernel doesn't have a metric that makes this easy to poll and set a threshold, but we can do a simple test on whether we're able to create a watch or not. This is the same principal used in the prometheus node exporter to detect this type of issue.
Also, I'm planning to add a sysctl check, but will do that as a separate PR.
> Add a checker that tests if inotify is able to create watches

- build.assets/grpc/Dockerfile
For this Dockerfile, I think we can just point to 1.10, and automatically grab the latest... thoughts?
> update to golang 1.10.7 to avoid cve-2018-16875

- agent/agent.go
- agent/serf.go
- agent/server_test.go
This is to fix the issues with serf dropping the connection (i.e. as a result of restarting the serf unit).
> Detect client closed situations and reinit the client.

- monitoring/dns.go
Updates https://github.com/gravitational/gravity/issues/257
Allow querying custom nameservers and doing NS record queries. Will be used for health checking upstream nameservers.
> allow querying custom resolvers and using NS queries

- agent/cache/multiplex/multiplex.go
- agent/proto/agentpb/timestamp.go
- monitoring/collector/utils.go
Hi, we updated some exported function comments based on best practices from [Effective Go](https://golang.org/doc/effective_go.html). It’s admittedly a relatively minor fix up. Does this help you?
> Fix function comments based on best practices from Effective Go

- monitoring/defaults_linux.go
- monitoring/sysctl_checkers.go
Updates https://github.com/gravitational/gravity.e/issues/4087
So, there's 2 potential gaps with these checks:
- I don't check that the advertise-ip interface (like ens4) has forwarding enabled. This would require detecting the name of the interface, but very weirdly, when I tried to test this on a test VM it doesn't seem like it's needed. It possible different versions/configurations of kubernetes or linux may change that, because I would expect forwarding to be needed for external traffic.
- This check can only run after the interface is created, which means we can't try and autofix these failures. A system with `net.ipv4.conf.default.forwarding = 0` will have new interfaces created without forwarding enabled, which we would have to workaround outside of satellite. Alternatively, we …
> Add sysctl checkers that per interface forwarding is enabled

- monitoring/sysctl.go
- monitoring/sysctl_test.go
Updates https://github.com/gravitational/gravity.e/issues/4044
Implements a checker for open file handles vs max file handles. I set it up so it will throw a health check failure if the number of allocatable file handles falls below a minimum value. IE if the max filehandles is 100, and the minimum value is set to 10, then when more than 90 filehandles are in use the health check fill fail.
> implement checker for file-nr

- monitoring/dns.go
- monitoring/dns_test.go
- monitoring/modules_linux_test.go
Updates gravitational/gravity#257
This switches the satellite DNS testing from using the default golang resolver to a more flexible external resolver. The primary reason to do this, is the embedded golang resolver doesn't consider `.` to be a valid DNS name, which prevents us from being able to run root system queries.
Due to the leaking DNS queries, we need to test the upstream DNS servers, and I think the most reliable way to do so is to perform a root system query.
> use third-party DNS resolver that supports root system queries

- monitoring/defaults_linux.go
Kubernetes by default has the range of 30000-32767 for NodePort assignment. However, it is not appropriate to ensure (and fail the install) if something is bound within this range, because Kubernetes will actually only choose open ports when assigning a NodePort. Additionally, this range can be changed via configuration, so hardcoding verification of it being unused with no way of changing it is problematic.
It would be great to backport this to 5.5.x as well, as currently we have to maintain a fork of Gravity.
See also https://community.gravitational.com/t/port-usage-and-verification/163/3
See also https://github.com/gravitational/gravity/pull/451
> Remove port range check for 30000-32767

- agent/agent.go
- agent/serf.go
- agent/server_test.go
Backport #95 by customer request
Updates https://github.com/gravitational/gravity/issues/754
* Detect client closed situations and reinit the client.
This is to fix the issues with serf dropping the connection.
* Protect client with a mutex
* Address review comments
> Detect client closed situations and reinit the client. (#95)

- monitoring/defaults_linux.go
Fixes https://github.com/gravitational/gravity/issues/735
Note: I haven't setup a test VM to explicitly test this.
> Filter CONFIG_NF_NAT_IPV4 / CONFIG_NF_NAT_NEEDED on recent kernels

- agent/server.go
- cmd/agent/agent.go
- cmd/agent/checkers.go
Addresses gravitational/gravity#806
Okay to just log returned errors from `serve` or should we handle errors and shutdown satellite agent in case of error?
> Log errors returned from serve(...)

- agent/agent.go
- agent/client.go
- agent/server.go
- agent/server_test.go
- monitoring/timedrift.go
This PR addresses the "correct status" portion of gravitational/gravity#750 .
While collecting status, if there are any pending status queries when the context times out, they will not be included in the recorded status.
Same situation with the health checks. Any probes that timeout will not be recorded.
Instead of ignoring the node statuses and health checks that timed out, satellite should record the statuses and probes with information indicating that the query failed due to timeout.
This change will cause satellite to no longer log the warnings on timeout. If we'd still like to log the warnings after timeout, we could use a WaitGroup and a separate goroutine to check if all status queries have returned by the time the context times out.
In the situation when a network partition is …
> Record status/probe in case of timeout.

- agent/agent.go
- cmd/agent/status.go
- Forgot to run satellite test. Satellite agent NewClient requires a context.
- Typo
> NewClient requires context

- monitoring/cgroup.go
- monitoring/cgroup_test.go
- utils/reader.go
- utils/reader_test.go
- utils/utils_test.go
- Use consistent receiver name 'c' for Checkers.
- Modify cgroup checker to comply with the provided context.
- Add test case to verify checker complies with context.
> Modify cgroup checker to comply with context
